
version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256